git_info:
  repo_url: https://github.com/your-repo.git
  gh_token: your_github_token
  author: author
  email: author_mail

rewriter:
  dry_run: true
  target_letters: "HELLO"
  background_commits_per_day: 16
  foreground_commits_per_day: 38
  leading_columns: 8
  trailing_columns: 0
  letter_spacing: 2
  font: "75"
